### ISSUE TITLE
Add portfolio

### ISSUE THREAD

**Issue by tchx84** [perrsona1234/PinePhone-openSUSE-Phosh#1]
Hey @perrsona1234 !

Dropping this here, in case you find it useful https://github.com/tchx84/portfolio

**Comment by tchx84** [comment]
> Hey @perrsona1234 !
> 
> Dropping this here, in case you find it useful https://github.com/tchx84/portfolio

Build from master, btw... things are moving fast,

**Comment by perrsona1234** [comment]
Will take a look, thanks.

**Comment by perrsona1234** [comment]
I decided to go with Index from Maui Project. https://mauikit.org/
