### ISSUE TITLE
Add Papirus Folder Color [Green]

### ISSUE THREAD

**Issue by LyrixCaz** [perrsona1234/PinePhone-openSUSE-Phosh#3]
It would be nice for the script to install papirus-folders and do "papirus-folders -t Papirus -C green" to change the default blue folder color to green, which SOMEWHAT matches the green highlights. 

BEFORE:
![photo_2021-01-02_22-44-08](https://user-images.githubusercontent.com/45947682/103471302-8b17bb00-4d76-11eb-93da-6fb4b98fea29.jpg)

AFTER:
![photo_2021-01-02_22-48-42](https://user-images.githubusercontent.com/45947682/103471306-97037d00-4d76-11eb-9d17-23cb32273727.jpg)

**Comment by perrsona1234** [comment]
Looks more like lime-green to me.

**Comment by perrsona1234** [comment]
I added it in V3.
